version: "3.9"

services:
  # app:
  #   build: .
  #   container_name: "birthday-remember_api"
  #   ports:
  #     - 3333:3333
  #   command: bash -c "npm run typeorm:development -- -d src/shared/infra/typeorm/index.ts migration:run && npm run dev:server"
  #   # command: bash -c "npm run test"
  #   volumes:
  #     - .:/user/app
  # queue:
  #   build: .
  #   container_name: "birthday-remember_queue"
  #   ports:
  #     - 6666:6666
  #   command: bash -c "npm run dev:queue"
  #   volumes:
  #     - .:/user/app
  database:
    image: "postgres"
    container_name: "postgres_birthday-remember"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=birthdayremember
      - POSTGRES_PASSWORD=birthdayremember
      - POSTGRES_DB=birthday-remember
      - PGTZ=UTC
      - TZ=UTC
    volumes:
      - pgdata:/data/postgres
  test_database:
    image: "postgres"
    container_name: "postgres_birthday-remember_tests"
    restart: "always"
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=birthdayremember
      - POSTGRES_PASSWORD=birthdayremember
      - POSTGRES_DB=birthday-remember_tests
      - PGTZ=UTC
    volumes:
      - pgdata:/data/postgres
  redis:
    image: "redis:alpine"
    container_name: "redis_birthday-remember"
    restart: "always"
    environment:
      - REDIS_PASSWORD=redispassword
    command: >
        --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
  test_redis:
    image: "redis:alpine"
    container_name: "redis_birthday-remember_tests"
    restart: "always"
    environment:
      - REDIS_PASSWORD=redispassword
    command: >
        --requirepass ${REDIS_PASSWORD}
    ports:
      - 63791:6379
volumes:
  pgdata:
    driver: local
